services:
  - type: web
    name: medplat-flask-frontend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn try:app
    plan: free
    envVars:
      - key: PORT
        value: 10000  # or any unused port above 10000

  - type: web
    name: medplat-rasa-server
    env: python
    buildCommand: |
      pip install -r requirements.txt
      rasa train
    startCommand: rasa run --enable-api --cors "*" --port 8080 --model models
    plan: free
    envVars:
      - key: PORT
        value: 8080

  - type: web
    name: medplat-actions
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: rasa run actions --port 5055
    plan: free
    envVars:
      - key: PORT
        value: 5055
