services:
  - type: web
    name: medplat-frontend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free

  - type: web
    name: medplat-rasa-server
    env: python
    buildCommand: |
      cd rasa_project
      pip install -r requirements.txt
      rasa train
    startCommand: cd rasa_project && rasa run --enable-api --cors "*" --port 8080
    plan: free

  - type: web
    name: medplat-actions
    env: python
    buildCommand: |
      cd rasa_project
      pip install -r requirements.txt
    startCommand: cd rasa_project && rasa run actions --port 5055
    plan: free

  - type: web
    name: medplat-middleware
    env: python
    buildCommand: |
      cd middleware
      pip install -r requirements.txt
    startCommand: cd middleware && gunicorn server:app
    plan: free
